// After `hardhat compile`: writes the game ABI + creation bytecode where the app imports them.
// usage: node scripts/export-abi.mjs   (from contracts/)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";

const artifact = JSON.parse(readFileSync(path.resolve("artifacts/contracts/StarminerGame.sol/StarminerGame.json"), "utf8"));
const out = path.resolve("../src/lib/abi/starminerGame.ts");
mkdirSync(path.dirname(out), { recursive: true });
writeFileSync(
  out,
  `/* GENERATED by contracts/scripts/export-abi.mjs from the compiled StarminerGame.sol — do not edit. */
export const STARMINER_GAME_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;

/** Creation bytecode: the deploy page appends the constructor arguments and sends it through the CREATE2 proxy. */
export const STARMINER_GAME_BYTECODE = "${artifact.bytecode}" as const;
`,
);
console.log("wrote", out, `(${artifact.abi.length} ABI entries, ${(artifact.bytecode.length - 2) / 2} bytes of bytecode)`);
