// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @dev GENERATED by scripts/gen-tables.ts — the same numbers the client uses. Do not edit.
library Tables {
    uint256 internal constant CAP_BPS = 9900;
    uint256 internal constant BELOW_STEPS = 16;
    uint256 internal constant ABOVE_STEPS = 24;
    uint256 internal constant ABOVE_RANGE_E6 = 1500000;

    function below() internal pure returns (uint16[17] memory t) {
        t = [uint16(5200), uint16(5465), uint16(5678), uint16(5875), uint16(6062), uint16(6242), uint16(6416), uint16(6587), uint16(6753), uint16(6917), uint16(7078), uint16(7236), uint16(7393), uint16(7547), uint16(7700), uint16(7851), uint16(8000)];
    }

    function above() internal pure returns (uint16[25] memory t) {
        t = [uint16(8000), uint16(8321), uint16(8591), uint16(8817), uint16(9007), uint16(9166), uint16(9300), uint16(9412), uint16(9507), uint16(9586), uint16(9652), uint16(9708), uint16(9755), uint16(9794), uint16(9827), uint16(9855), uint16(9878), uint16(9898), uint16(9900), uint16(9900), uint16(9900), uint16(9900), uint16(9900), uint16(9900), uint16(9900)];
    }

    function levelXp() internal pure returns (uint32[30] memory t) {
        t = [uint32(0), uint32(80), uint32(300), uint32(650), uint32(1110), uint32(1700), uint32(2410), uint32(3230), uint32(4160), uint32(5200), uint32(6350), uint32(7620), uint32(8990), uint32(10460), uint32(12040), uint32(13730), uint32(15520), uint32(17420), uint32(19410), uint32(21510), uint32(23720), uint32(26020), uint32(28420), uint32(30930), uint32(33530), uint32(36240), uint32(39040), uint32(41950), uint32(44950), uint32(48040)];
    }
}
