// Generates the lookup tables the client and the contract share, from the analytic config.
// usage: node --import ./tests/register.mjs scripts/gen-tables.ts
// → src/game/math/tables.ts and contracts/contracts/Tables.sol
import { mkdirSync, writeFileSync } from "node:fs";
import { MISSIONS } from "@/game/config/missions";
import { PROGRESSION } from "@/game/config/progression";

const { atMinimum, atRecommended, cap, decay, belowExponent } = MISSIONS.curve;

/** 16 intervals over t ∈ [0, 1] (minimum → recommended). */
const BELOW_STEPS = 16;
/** 24 intervals over ratio ∈ [1, 2.5] — 16 per unit of ratio, so the ratio maps to the grid with one multiply. */
const ABOVE_STEPS = 24;
const ABOVE_RANGE = 1.5;
const CAP_BPS = Math.round(cap * 10000);

const below = Array.from({ length: BELOW_STEPS + 1 }, (_, i) => {
  const t = i / BELOW_STEPS;
  return Math.round((atMinimum + (atRecommended - atMinimum) * Math.pow(t, belowExponent)) * 10000);
});
const above = Array.from({ length: ABOVE_STEPS + 1 }, (_, i) => {
  const r = 1 + (i * ABOVE_RANGE) / ABOVE_STEPS;
  return Math.min(CAP_BPS, Math.round((1 - (1 - atRecommended) * Math.exp(-decay * (r - 1))) * 10000));
});
const levels = Array.from({ length: PROGRESSION.maxLevel }, (_, i) => PROGRESSION.xpForLevel(i + 1));

const ts = `/* GENERATED by scripts/gen-tables.ts from config/missions.ts and config/progression.ts — do not edit. */
/* The contract carries the same tables (contracts/contracts/Tables.sol); both interpolate them identically. */

/** Success chance in bps from minimum (t = 0) to recommended (t = 1), ${BELOW_STEPS} intervals. */
export const CURVE_BELOW_BPS = [${below.join(", ")}] as const;
/** Success chance in bps from ratio 1 to ratio ${1 + ABOVE_RANGE}, ${ABOVE_STEPS} intervals (${ABOVE_STEPS / ABOVE_RANGE} per unit of ratio). */
export const CURVE_ABOVE_BPS = [${above.join(", ")}] as const;
export const CURVE_ABOVE_RANGE_E6 = ${Math.round(ABOVE_RANGE * 1e6)};
export const CURVE_CAP_BPS = ${CAP_BPS};
/** Total XP needed to be level n (index n − 1). */
export const LEVEL_XP = [${levels.join(", ")}] as const;
`;

const sol = `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @dev GENERATED by scripts/gen-tables.ts — the same numbers the client uses. Do not edit.
library Tables {
    uint256 internal constant CAP_BPS = ${CAP_BPS};
    uint256 internal constant BELOW_STEPS = ${BELOW_STEPS};
    uint256 internal constant ABOVE_STEPS = ${ABOVE_STEPS};
    uint256 internal constant ABOVE_RANGE_E6 = ${Math.round(ABOVE_RANGE * 1e6)};

    function below() internal pure returns (uint16[${BELOW_STEPS + 1}] memory t) {
        t = [${below.map((v) => `uint16(${v})`).join(", ")}];
    }

    function above() internal pure returns (uint16[${ABOVE_STEPS + 1}] memory t) {
        t = [${above.map((v) => `uint16(${v})`).join(", ")}];
    }

    function levelXp() internal pure returns (uint32[${levels.length}] memory t) {
        t = [${levels.map((v) => `uint32(${v})`).join(", ")}];
    }
}
`;

writeFileSync("src/game/math/tables.ts", ts);
mkdirSync("contracts/contracts", { recursive: true });
writeFileSync("contracts/contracts/Tables.sol", sol);
console.log("below", below.join(" "));
console.log("above", above.join(" "));
console.log("levels", levels.join(" "));
