/* GENERATED by scripts/gen-tables.ts from config/missions.ts and config/progression.ts — do not edit. */
/* The contract carries the same tables (contracts/contracts/Tables.sol); both interpolate them identically. */

/** Success chance in bps from minimum (t = 0) to recommended (t = 1), 16 intervals. */
export const CURVE_BELOW_BPS = [5200, 5465, 5678, 5875, 6062, 6242, 6416, 6587, 6753, 6917, 7078, 7236, 7393, 7547, 7700, 7851, 8000] as const;
/** Success chance in bps from ratio 1 to ratio 2.5, 24 intervals (16 per unit of ratio). */
export const CURVE_ABOVE_BPS = [8000, 8321, 8591, 8817, 9007, 9166, 9300, 9412, 9507, 9586, 9652, 9708, 9755, 9794, 9827, 9855, 9878, 9898, 9900, 9900, 9900, 9900, 9900, 9900, 9900] as const;
export const CURVE_ABOVE_RANGE_E6 = 1500000;
export const CURVE_CAP_BPS = 9900;
/** Total XP needed to be level n (index n − 1). */
export const LEVEL_XP = [0, 80, 300, 650, 1110, 1700, 2410, 3230, 4160, 5200, 6350, 7620, 8990, 10460, 12040, 13730, 15520, 17420, 19410, 21510, 23720, 26020, 28420, 30930, 33530, 36240, 39040, 41950, 44950, 48040] as const;
